# Generated by Django 4.0.4 on 2022-05-13 02:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BridgeResponseErrorPayload',
            fields=[
                ('errorId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.CharField(blank=True, max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='BridgeResponseFolders',
            fields=[
                ('folderId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('folderPath', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('folderName', models.CharField(max_length=1000)),
                ('userName', models.CharField(max_length=10000)),
                ('priv', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BridgeResponsePayload',
            fields=[
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('responseStatus', models.CharField(max_length=100)),
                ('errors', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bridge.bridgeresponseerrorpayload')),
                ('folderPaths', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge.bridgeresponsefolders')),
                ('originalRequest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bridge.payload')),
            ],
        ),
        migrations.CreateModel(
            name='BridgeResponse',
            fields=[
                ('requestId', models.UUIDField(primary_key=True, serialize=False)),
                ('requestedAction', models.CharField(max_length=1000)),
                ('statusCode', models.CharField(max_length=100)),
                ('responsePayload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge.bridgeresponsepayload')),
            ],
        ),
        migrations.CreateModel(
            name='Bridge',
            fields=[
                ('requestId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requestedAction', models.CharField(max_length=1000)),
                ('requestedPayload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge.payload')),
            ],
        ),
    ]
